import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { join } from "node:path";
import test from "node:test";

const root = fileURLToPath(new URL("../..", import.meta.url));
const auth = await import(pathToFileURL(join(root, "packages/auth/dist/index.js")).href);
const config = await import(pathToFileURL(join(root, "packages/config/dist/index.js")).href);
const domain = await import(pathToFileURL(join(root, "packages/domain/dist/index.js")).href);
const events = await import(pathToFileURL(join(root, "packages/events/dist/index.js")).href);
const lifecycle = await import(pathToFileURL(join(root, "packages/session-application/dist/index.js")).href);
const runtime = await import(pathToFileURL(join(root, "packages/session-runtime/dist/index.js")).href);
const turns = await import(pathToFileURL(join(root, "packages/turns/dist/index.js")).href);

const tenantAlpha = id(1);
const tenantBeta = id(2);
const actorAlpha = id(3);
const actorBeta = id(4);
const participantAlpha = id(5);
const participantOther = id(6);
const presenterAlpha = id(7);
const presenterOther = id(8);
const agentAlpha = id(9);
const agentBeta = id(10);
const trace = { trace_id: "a".repeat(32), correlation_id: id(11) };
const participantBeta = id(12);

function id(offset) {
  return domain.uuidV7FromParts(
    1_703_000_000_000 + offset,
    Uint8Array.from(Array.from({ length: 10 }, (_, index) => (offset + index + 1) & 0xff)),
  );
}

function ids(start = 100) {
  let offset = start;
  return { nextId: () => id(offset++) };
}

function runtimeConfiguration() {
  return config.loadRuntimeConfig({
    AXTRO_ENV: "test",
    AXTRO_SERVICE_NAME: "api",
    AXTRO_PROVIDER_MODE: "fake",
    AXTRO_SECRET_BROKER_HANDLE: "secret://local/turn-driver-tests",
    AXTRO_PORT: "3000",
    AXTRO_REQUEST_TIMEOUT_MS: "10000",
    AXTRO_DEV_AUTH_ENABLED: "true",
    AXTRO_LOG_LEVEL: "info",
  });
}

function requestFor(tenantId, actorId, token, { purposes = ["essential_processing"], scopes = ["session:read", "session:write"] } = {}) {
  const verifier = auth.createDevelopmentIdentityVerifier(runtimeConfiguration(), [{
    token,
    actorId,
    actorType: "workflow",
    identityKind: "service",
    tenantGrants: [{ tenantId, grantedScopes: scopes, purposes }],
  }]);
  return auth.resolveAuthorizedRequestContext({ authorization: `Bearer ${token}`, requestedTenantId: tenantId }, verifier);
}

function manualTimers() {
  let nextId = 0;
  const callbacks = new Map();
  return {
    scheduler: {
      setTimeout(callback, delayMs) {
        const timerId = nextId += 1;
        callbacks.set(timerId, { callback, delayMs });
        return timerId;
      },
      clearTimeout(timerId) {
        callbacks.delete(timerId);
      },
    },
    fireAll() {
      const pending = [...callbacks.values()];
      callbacks.clear();
      for (const timer of pending) timer.callback();
    },
    count() {
      return callbacks.size;
    },
  };
}

function controlledFastLane() {
  const requests = [];
  const pending = [];
  let resolveRequested;
  const requested = new Promise((resolve) => { resolveRequested = resolve; });
  return {
    port: {
      async respond(request, control) {
        requests.push({ request, control });
        resolveRequested();
        return new Promise((resolve) => pending.push({ resolve }));
      },
    },
    async waitForRequest() {
      await requested;
      assert.equal(requests.length, 1);
      return requests[0];
    },
    release(response = deterministicResponse()) {
      const current = pending.shift();
      assert.ok(current);
      current.resolve(response);
    },
  };
}

function deterministicResponse() {
  return {
    response_text: "Thank you. I am ready to continue the conversation.",
    patch: {
      active_topic: "next_step",
      open_questions: [],
      repair_state: "none",
      incremental_summary: "Presenter response generated by a deterministic local fake.",
    },
  };
}

async function fixture({ fastLane, timeoutScheduler, fastLaneTimeoutMs, purposeAlpha, driverIds = ids(300) } = {}) {
  const outbox = events.createDeterministicTransactionalOutboxRepository();
  const application = lifecycle.createDeterministicSessionLifecycleApplication({
    outbox,
    registrations: [
      {
        tenant_id: tenantAlpha,
        agent_id: agentAlpha,
        role_pack_id: "sales-closer",
        role_pack_version: "1.0.0",
        presenter_id: presenterAlpha,
      },
      {
        tenant_id: tenantBeta,
        agent_id: agentBeta,
        role_pack_id: "sales-closer",
        role_pack_version: "1.0.0",
        presenter_id: presenterOther,
      },
    ],
    idGenerator: ids(100),
    clock: { now: () => 1_703_000_000_000 },
    store: lifecycle.createDeterministicSessionLifecycleStore(),
  });
  const alpha = requestFor(tenantAlpha, actorAlpha, "dev_turn_alpha_0001", purposeAlpha === undefined ? {} : { purposes: purposeAlpha });
  const beta = requestFor(tenantBeta, actorBeta, "dev_turn_beta_0001");
  const created = await application.createSession(alpha, {
    agent_id: agentAlpha,
    role_pack_id: "sales-closer",
    role_pack_version: "1.0.0",
    channel: "api",
    language: "en-US",
  }, "create-turn-session-0001", trace);
  await application.activateSession(alpha, created.session_id, {
    presenter_id: presenterAlpha,
    expected_state_version: created.state_version,
  }, "activate-turn-session-0001", trace);
  const betaCreated = await application.createSession(beta, {
    agent_id: agentBeta,
    role_pack_id: "sales-closer",
    role_pack_version: "1.0.0",
    channel: "api",
    language: "en-US",
  }, "create-turn-session-beta-0001", trace);
  await application.activateSession(beta, betaCreated.session_id, {
    presenter_id: presenterOther,
    expected_state_version: betaCreated.state_version,
  }, "activate-turn-session-beta-0001", trace);
  const actors = runtime.createSessionActorRegistry({
    source: turns.createOutboxSessionActorReplaySource(outbox),
    clock: { now: () => 1_703_000_000_000 },
  });
  const driver = turns.createTurnDriver({
    outbox,
    actors,
    participants: turns.createDeterministicTurnParticipantDirectory([
      {
        tenant_id: tenantAlpha,
        session_id: created.session_id,
        participant_id: participantAlpha,
        authenticated_actor_id: actorAlpha,
      },
      {
        tenant_id: tenantBeta,
        session_id: betaCreated.session_id,
        participant_id: participantBeta,
        authenticated_actor_id: actorBeta,
      },
    ]),
    fast_lane: fastLane ?? turns.createDeterministicFastLaneFake({ patch: deterministicResponse().patch }),
    clock: { now: () => 1_703_000_000_000 },
    id_generator: driverIds,
    ...(timeoutScheduler === undefined ? {} : { timeout_scheduler: timeoutScheduler }),
    ...(fastLaneTimeoutMs === undefined ? {} : { fast_lane_timeout_ms: fastLaneTimeoutMs }),
  });
  return {
    outbox,
    application,
    actors,
    driver,
    alpha,
    beta,
    sessionId: created.session_id,
    betaSessionId: betaCreated.session_id,
  };
}

function submitInput(text, clientTurnId, speakerParticipantId = participantAlpha) {
  return {
    schema_version: "2.0.0",
    speaker_participant_id: speakerParticipantId,
    text,
    language: "en-US",
    client_turn_id: clientTurnId,
  };
}

function interruptionInput(generationId, clientInterruptId) {
  return {
    speaker_participant_id: participantAlpha,
    generation_id: generationId,
    client_interrupt_id: clientInterruptId,
  };
}

function timeline(outbox, request, sessionId) {
  return outbox.listOutbox(request)
    .filter((record) => record.aggregate_id === sessionId)
    .sort((left, right) => left.aggregate_version - right.aggregate_version);
}

async function changePresenter({ outbox, actors, alpha, sessionId }, presenterId, eventId = id(700)) {
  const state = outbox.readInteractionAggregate(alpha, sessionId);
  assert.ok(state);
  const event = {
    schema_version: "2.0.0",
    event_id: eventId,
    event_type: "presenter.changed",
    event_version: 1,
    aggregate_type: "interaction_session",
    aggregate_id: sessionId,
    aggregate_version: state.session.state_version + 1,
    tenant_id: tenantAlpha,
    session_id: sessionId,
    producer: "tests.turn-driver",
    trace_id: trace.trace_id,
    correlation_id: trace.correlation_id,
    causation_id: timeline(outbox, alpha, sessionId).at(-1).event_id,
    data_classification: "internal",
    occurred_at: "2026-07-14T12:00:00.000Z",
    payload: {
      expected_presenter_id: presenterAlpha,
      presenter_id: presenterId,
    },
  };
  const committed = await outbox.commitInteractionEvent(alpha, event);
  const actor = await actors.getActor(alpha, sessionId);
  await actor.applyCanonicalEvent(alpha, committed.outbox.event);
}

test("three textual participant turns create a continuous canonical timeline and deterministic Presenter responses", async () => {
  const value = await fixture();
  const results = [];
  for (const [index, text] of ["First question", "Second question", "Third question"].entries()) {
    results.push(await value.driver.submitTurn(
      value.alpha,
      value.sessionId,
      submitInput(text, `client-turn-${String(index + 1).padStart(8, "0")}`),
      `idempotency-turn-${String(index + 1).padStart(8, "0")}`,
      trace,
    ));
  }
  assert.equal(results.every((result) => result.response_text === deterministicResponse().response_text), true);
  const events = timeline(value.outbox, value.alpha, value.sessionId);
  assert.deepEqual(events.map((record) => record.event.event_type), [
    "session.created",
    "session.prepared",
    "disclosure.delivered",
    "consent.recorded",
    "session.activated",
    "turn.committed",
    "turn.committed",
    "turn.committed",
    "turn.committed",
    "turn.committed",
    "turn.committed",
  ]);
  assert.deepEqual(events.map((record) => record.aggregate_version), Array.from({ length: 11 }, (_, index) => index + 1));
  const turnsOnly = events.filter((record) => record.event.event_type === "turn.committed");
  assert.deepEqual(turnsOnly.map((record) => record.event.data_classification), Array(6).fill("restricted"));
  assert.deepEqual(turnsOnly.map((record) => JSON.parse(record.event.payload_json).speaker_role), [
    "participant", "presenter", "participant", "presenter", "participant", "presenter",
  ]);
  const actor = await value.actors.getActor(value.alpha, value.sessionId);
  const state = await actor.getState(value.alpha);
  assert.equal(state.session.state_version, 11);
  assert.equal(state.conversation.turn_index, 6);
  assert.equal(state.conversation.active_topic, "next_step");
  assert.equal(state.conversation.incremental_summary, deterministicResponse().patch.incremental_summary);
  assert.equal(state.conversation.repair_state, "none");
  assert.equal(results.at(-1).state_hash, domain.interactionStateHash(state));
  assert.deepEqual(value.driver.getMetrics(value.alpha, value.sessionId), {
    participant_turns_committed: 3,
    presenter_turns_committed: 3,
    interruptions_committed: 0,
    generations_cancelled: 0,
    late_outputs_discarded: 0,
    fast_lane_failures: 0,
    fast_lane_timeouts: 0,
    last_fast_lane_duration_ms: 0,
  });
});

test("floor change invalidates a delayed Fast Lane response and the reducer rejects an old Presenter atomically", async () => {
  const controlled = controlledFastLane();
  const value = await fixture({ fastLane: controlled.port });
  const pending = value.driver.submitTurn(
    value.alpha,
    value.sessionId,
    submitInput("Delayed floor request", "client-floor-0001"),
    "idempotency-floor-0001",
    trace,
  );
  await controlled.waitForRequest();
  await changePresenter(value, presenterOther);
  controlled.release();
  await assert.rejects(pending, turns.TurnDriverGenerationCancelledError);
  const timelineRecords = timeline(value.outbox, value.alpha, value.sessionId);
  assert.deepEqual(timelineRecords.slice(-2).map((record) => record.event.event_type), ["turn.committed", "presenter.changed"]);
  assert.equal(timelineRecords.some((record) => record.event.event_type === "turn.committed"
    && JSON.parse(record.event.payload_json).speaker_participant_id === presenterAlpha), false);
  const state = value.outbox.readInteractionAggregate(value.alpha, value.sessionId);
  assert.ok(state);
  await assert.rejects(
    value.outbox.commitInteractionEvent(value.alpha, {
      schema_version: "2.0.0",
      event_id: id(701),
      event_type: "turn.committed",
      event_version: 1,
      aggregate_type: "interaction_session",
      aggregate_id: value.sessionId,
      aggregate_version: state.session.state_version + 1,
      tenant_id: tenantAlpha,
      session_id: value.sessionId,
      producer: "tests.turn-driver",
      trace_id: trace.trace_id,
      correlation_id: trace.correlation_id,
      causation_id: timelineRecords.at(-1).event_id,
      data_classification: "restricted",
      occurred_at: "2026-07-14T12:00:01.000Z",
      payload: {
        schema_version: "2.0.0",
        speaker_participant_id: presenterAlpha,
        speaker_role: "presenter",
        transcript_text: "Old Presenter output must not commit.",
        generation_id: 1,
        turn_index: state.conversation.turn_index + 1,
        active_topic: null,
        language: "en-US",
        open_questions: [],
        confirmed_facts: [],
        repair_state: "none",
        incremental_summary: "Late output.",
      },
    }),
    domain.InteractionTransitionError,
  );
  assert.equal(value.driver.getMetrics(value.alpha, value.sessionId).late_outputs_discarded, 1);
});

test("interruption fences a resolved Fast Lane before its Presenter commit, is idempotent, and updates recovery state", async () => {
  const controlled = controlledFastLane();
  const value = await fixture({ fastLane: controlled.port });
  const pending = value.driver.submitTurn(
    value.alpha,
    value.sessionId,
    submitInput("Please stop", "client-interrupt-turn"),
    "idempotency-interrupt-turn",
    trace,
  );
  const request = await controlled.waitForRequest();
  controlled.release();
  const firstInterruption = value.driver.interruptTurn(
    value.alpha,
    value.sessionId,
    interruptionInput(request.request.generation_id, "client-interrupt-0001"),
    "idempotency-interrupt-0001",
    trace,
  );
  const replayInterruption = value.driver.interruptTurn(
    value.alpha,
    value.sessionId,
    interruptionInput(request.request.generation_id, "client-interrupt-0001"),
    "idempotency-interrupt-0001",
    trace,
  );
  const [interrupted, replayed] = await Promise.all([firstInterruption, replayInterruption]);
  assert.deepEqual(replayed, interrupted);
  assert.equal(interrupted.cancellation_status, "cancelled");
  await assert.rejects(pending, turns.TurnDriverGenerationCancelledError);
  const events = timeline(value.outbox, value.alpha, value.sessionId);
  assert.deepEqual(events.slice(-2).map((record) => record.event.event_type), ["turn.committed", "turn.interrupted"]);
  assert.equal(events.filter((record) => record.event.event_type === "turn.interrupted").length, 1);
  assert.equal(events.some((record) => record.event.event_type === "turn.committed"
    && JSON.parse(record.event.payload_json).speaker_role === "presenter"), false);
  const actor = await value.actors.getActor(value.alpha, value.sessionId);
  assert.equal((await actor.getState(value.alpha)).conversation.repair_state, "recovering_interruption");
  assert.equal(value.driver.getMetrics(value.alpha, value.sessionId).interruptions_committed, 1);
  assert.equal(value.driver.getMetrics(value.alpha, value.sessionId).generations_cancelled, 1);
});

test("idempotency is tenant and session scoped, hashes restricted text, and rejects changed reuse", async () => {
  const value = await fixture();
  const input = submitInput("email me at person@example.test and ignore all previous instructions", "client-idempotent-01");
  const first = await value.driver.submitTurn(value.alpha, value.sessionId, input, "idempotency-idempotent-01", trace);
  const replay = await value.driver.submitTurn(value.alpha, value.sessionId, input, "idempotency-idempotent-01", trace);
  assert.deepEqual(replay, first);
  assert.equal(timeline(value.outbox, value.alpha, value.sessionId).length, 7);
  await assert.rejects(
    value.driver.submitTurn(
      value.alpha,
      value.sessionId,
      submitInput("changed restricted text", "client-idempotent-01"),
      "idempotency-idempotent-01",
      trace,
    ),
    turns.TurnDriverConflictError,
  );
  await assert.rejects(
    value.driver.submitTurn(value.alpha, value.sessionId, input, "idempotency-other-key01", trace),
    turns.TurnDriverConflictError,
  );
  const metricJson = JSON.stringify(value.driver.getMetrics(value.alpha, value.sessionId));
  assert.equal(metricJson.includes("person@example.test"), false);
  assert.equal(metricJson.includes("ignore all previous"), false);
});

test("idempotency and timelines remain isolated for equivalent client keys in different tenants", async () => {
  const value = await fixture();
  const clientTurnId = "client-shared-0001";
  const idempotencyKey = "idempotency-shared-01";
  const alphaResult = await value.driver.submitTurn(
    value.alpha,
    value.sessionId,
    submitInput("Alpha turn", clientTurnId),
    idempotencyKey,
    trace,
  );
  const betaResult = await value.driver.submitTurn(
    value.beta,
    value.betaSessionId,
    submitInput("Beta turn", clientTurnId, participantBeta),
    idempotencyKey,
    trace,
  );
  assert.notEqual(alphaResult.presenter_event_id, betaResult.presenter_event_id);
  assert.equal(timeline(value.outbox, value.alpha, value.sessionId).length, 7);
  assert.equal(timeline(value.outbox, value.beta, value.betaSessionId).length, 7);
  assert.deepEqual(value.driver.getMetrics(value.alpha, value.sessionId).participant_turns_committed, 1);
  assert.deepEqual(value.driver.getMetrics(value.beta, value.betaSessionId).participant_turns_committed, 1);
});

test("participant directory rejects duplicate speaking authority and stale interruptions cannot write markers", async () => {
  assert.throws(
    () => turns.createDeterministicTurnParticipantDirectory([
      {
        tenant_id: tenantAlpha,
        session_id: id(50),
        participant_id: participantAlpha,
        authenticated_actor_id: actorAlpha,
      },
      {
        tenant_id: tenantAlpha,
        session_id: id(50),
        participant_id: participantAlpha,
        authenticated_actor_id: actorBeta,
      },
    ]),
    turns.TurnDriverConfigurationError,
  );
  const value = await fixture();
  const result = await value.driver.submitTurn(
    value.alpha,
    value.sessionId,
    submitInput("Completed turn", "client-completed-001"),
    "idempotency-completed-01",
    trace,
  );
  const before = timeline(value.outbox, value.alpha, value.sessionId).length;
  await assert.rejects(
    value.driver.interruptTurn(
      value.alpha,
      value.sessionId,
      interruptionInput(result.generation_id, "client-stale-0001"),
      "idempotency-stale-0001",
      trace,
    ),
    turns.TurnDriverConflictError,
  );
  assert.equal(timeline(value.outbox, value.alpha, value.sessionId).length, before);
  const actor = await value.actors.getActor(value.alpha, value.sessionId);
  assert.equal((await actor.getState(value.alpha)).conversation.repair_state, "none");
});

test("forged speaker, wrong tenant, and missing essential purpose fail before a canonical write", async () => {
  const value = await fixture();
  const forged = { ...submitInput("Forged speaker", "client-forged-0001"), speaker_participant_id: participantOther };
  await assert.rejects(
    value.driver.submitTurn(value.alpha, value.sessionId, forged, "idempotency-forged-01", trace),
    turns.TurnDriverAuthorizationError,
  );
  await assert.rejects(
    value.driver.submitTurn(value.beta, value.sessionId, submitInput("Wrong tenant", "client-tenant-0001"), "idempotency-tenant-01", trace),
    turns.TurnDriverAuthorizationError,
  );
  const noPurpose = await fixture({ purposeAlpha: ["provider_auth"] });
  await assert.rejects(
    noPurpose.driver.submitTurn(noPurpose.alpha, noPurpose.sessionId, submitInput("No purpose", "client-purpose-0001"), "idempotency-purpose-01", trace),
    turns.TurnDriverAuthorizationError,
  );
  assert.equal(timeline(value.outbox, value.alpha, value.sessionId).length, 5);
});

test("Fast Lane timeout and invalid output leave the participant turn auditably committed without a Presenter response", async () => {
  const timers = manualTimers();
  let resolveHangingStarted;
  const hangingStarted = new Promise((resolve) => { resolveHangingStarted = resolve; });
  const hanging = {
    async respond() {
      resolveHangingStarted();
      return new Promise(() => {});
    },
  };
  const timed = await fixture({ fastLane: hanging, timeoutScheduler: timers.scheduler, fastLaneTimeoutMs: 10 });
  const pending = timed.driver.submitTurn(
    timed.alpha,
    timed.sessionId,
    submitInput("Timeout me", "client-timeout-0001"),
    "idempotency-timeout-01",
    trace,
  );
  await Promise.race([
    hangingStarted,
    pending.then(
      () => { throw new Error("Fast Lane command resolved before the test fake began"); },
      (error) => { throw error; },
    ),
  ]);
  assert.equal(timers.count(), 1);
  timers.fireAll();
  await assert.rejects(pending, turns.TurnDriverTimeoutError);
  assert.deepEqual(timeline(timed.outbox, timed.alpha, timed.sessionId).slice(-1).map((record) => record.event.event_type), ["turn.committed"]);
  const timedActor = await timed.actors.getActor(timed.alpha, timed.sessionId);
  assert.equal(timedActor.canPublishGeneration(timed.alpha, 1), false);
  assert.equal(timed.driver.getMetrics(timed.alpha, timed.sessionId).fast_lane_timeouts, 1);

  const invalid = await fixture({
    fastLane: {
      async respond() {
        return { response_text: "text", patch: { active_topic: null, open_questions: [], repair_state: "none", incremental_summary: "ok" }, action_intent: { tool: "forbidden" } };
      },
    },
  });
  await assert.rejects(
    invalid.driver.submitTurn(invalid.alpha, invalid.sessionId, submitInput("Invalid fake", "client-invalid-0001"), "idempotency-invalid-01", trace),
    turns.TurnDriverFastLaneError,
  );
  assert.deepEqual(timeline(invalid.outbox, invalid.alpha, invalid.sessionId).slice(-1).map((record) => record.event.event_type), ["turn.committed"]);
  assert.equal(invalid.driver.getMetrics(invalid.alpha, invalid.sessionId).fast_lane_failures, 1);
});

test("trusted request cancellation aborts Fast Lane work and cleans up the active generation", async () => {
  const controlled = controlledFastLane();
  const value = await fixture({ fastLane: controlled.port });
  const requestController = new AbortController();
  const pending = value.driver.submitTurn(
    value.alpha,
    value.sessionId,
    submitInput("Cancel this request", "client-request-cancel"),
    "idempotency-request-can",
    trace,
    {
      assertActive() {},
      signal: requestController.signal,
    },
  );
  const fastLaneRequest = await controlled.waitForRequest();
  requestController.abort();
  await assert.rejects(pending, turns.TurnDriverGenerationCancelledError);
  assert.equal(fastLaneRequest.control.signal.aborted, true);
  const actor = await value.actors.getActor(value.alpha, value.sessionId);
  assert.equal(actor.canPublishGeneration(value.alpha, fastLaneRequest.request.generation_id), false);
  assert.deepEqual(timeline(value.outbox, value.alpha, value.sessionId).slice(-1).map((record) => record.event.event_type), ["turn.committed"]);
  controlled.release();
});

test("the textual boundary contains no synchronous Axtro Agent, tool, provider, or media import", () => {
  const source = readFileSync(join(root, "packages/turns/src/index.ts"), "utf8").toLowerCase();
  for (const forbidden of ["@axtro/tool-runtime", "@axtro/policy", "@axtro/provider", "axtro agent", "tts", "avatar", "livekit"]) {
    assert.equal(source.includes(forbidden), false, `unexpected critical-path dependency: ${forbidden}`);
  }
});
